#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 10 23:26:23 2017

@author: ccartagena
"""

import numpy as np
import matplotlib.pylab as plt

distance = np.zeros(100)

for i in range(100):
    distance[i] = 0.28 * i
sine_data = 0.3220375 * np.sin((0.00458845*distance* - 0.00701485)*180/np.pi)

plt.plot(distance, sine_data)